### ISSUE TITLE
Version 0.2 doesn't work with AMD formatter

### ISSUE THREAD

**Issue by szwacz** [ryanseddon/gulp-es6-module-transpiler#18]
I can't get new transpiler to work with [AMD formatter](https://github.com/caridy/es6-module-transpiler-amd-formatter). Version 0.2 expects always to be one module (through `moduleName`), but every AMD module should be outputted to separate file. What happens is that all files are saved (one owerwrites another) to the same path (e.g. `bundle.js`).

I don't have good fix for this problem, so I'm starting this discussion. Some special magic value for `moduleName` which switches to "not bundling" behaviour comes to my mind, but this is dirty solution. Has anyone better idea?

**Comment by ryanseddon** [comment]
@rkusa @janjakubnanista any thoughts on this?

**Comment by janjakubnanista** [comment]
@ryanseddon New version of es6-module-transpiler supports ```bundle``` and ```commonjs``` formatters only by default. In order to output to AMD, you can use [es6-module-transpiler-amd-formatter](https://github.com/caridy/es6-module-transpiler-amd-formatter) module.

**Comment by janjakubnanista** [comment]
@ryanseddon @rkusa Could you please review & merge this minor change in README? Thanks guys

**Comment by szwacz** [comment]
@janjakubnanista Yes, as I linked in my previous post official AMD formatter is what I'm using, and this issue is about this formatter. I'm not fluent in how the whole gulp -> es6 transpiler -> AMD formatter works, but by looking at code in this repo `lib/index.js`:
```js
container.convert().forEach(function(converted) {
  var convertedAsFile = new gutil.File({
    path: moduleName + '.js'
  });
```
I think the problem is caused by this project. All files sent to gulp pipeline are forced to have the same name.

**Comment by janjakubnanista** [comment]
Oh sorry, I missed the start of discussion since I was reading it via gmail. I'll take a look since this was one of the trickier parts of the code. I'll get back to you ASAP.

**Comment by janjakubnanista** [comment]
@szwacz In meantime, you could work around this issue by creating multiple streams, one per module. Then, using [merge-stream](https://www.npmjs.com/package/merge-stream) you could merge these streams and write output with one gulp.dest.

**Comment by janjakubnanista** [comment]
@ryanseddon @rkusa Hi guys, could you please review the pull request?

**Comment by rkusa** [comment]
@janjakubnanista Code looks fine. However, how to get the bundle formatter to work? I was thinking about:

```js
gulp.task('bundle', function() {
  return gulp.src('src/**/*.js')
    .pipe(sourcemaps.init())
      .pipe(transpile({
        formatter: 'bundle'
      }))
      .pipe(concat('bundleName.js'))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('dist'))
})
```

But I was not able to get this to work properly. Any ideas?

**Comment by janjakubnanista** [comment]
@rkusa The problem is that you are using concat *before* writing sourceMaps. I think this cannot be accomplished by simple `gulp-concat`, you have to use [gulp-concat-sourcemap](https://www.npmjs.com/package/gulp-concat-sourcemap) plugin.

**Comment by rkusa** [comment]
@janjakubnanista According to [gulp-sourcemaps wiki](https://github.com/floridoo/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support) is `gulp-concat` compatible to `gulp-sourcemaps`, i.e. it should be - in theory - possible to chain multiple plugins between the `init` and `write` calls. I could try to fix the `gulp-concat` issue (next week).

**Comment by janjakubnanista** [comment]
@rkusa I've added e2e tests for sourcemaps functionality. There were two problems - one with `basePath` property passed to converted file, another with double `//# sourceMappingURL=...` comment that should have not been added to converted files by our plugin (`gulp-sourcemaps` is responsible for this).

**Comment by rkusa** [comment]
@janjakubnanista Awesome, works perfectly fine! wearefractal/gulp-concat#55 seems to be the only remaining issue.

**Comment by janjakubnanista** [comment]
I haven't seen that issue before, how does it affect this module?

**Comment by rkusa** [comment]
@janjakubnanista the `name` property of the generated source map is empty, making the source map useless (btw I've linked the wrong issue in the first place)

**Comment by janjakubnanista** [comment]
@rkusa I have tested output source maps. I have created HTML file in `test/` folder of our module:

    <html>
    <head>
        <script src="output/bundle.js"></script>
    </head>
    <body></body>
    </html>

If you run the e2e.js test (the one for concat()) and open this HTML in Chrome, everything should work fine - I can see both source files in Sources tab of DevTools.

**Comment by rkusa** [comment]
@janjakubnanista You're right! I think I miss understood source maps. Maybe they are just for compressed JavaScript files. So everything works fine! Well done @janjakubnanista

**Comment by szwacz** [comment]
Works brilliantly now. Thanks!

**Comment by szwacz** [comment]
Please publish to NPM.

**Comment by JackCA** [comment]
Yes, please publish! Just ran into this issue

**Comment by janjakubnanista** [comment]
@ryanseddon @rkusa Hi guys, could you please publish the newest version to NPM? I can't do it myself since I'm not a maintainer of the package. Thanks

**Comment by rkusa** [comment]
@janjakubnanista I don't have NPM publishing rights, too. So @ryanseddon please publish ;-)
