### ISSUE TITLE
The npm version only outputs a single file

### ISSUE THREAD

**Issue by simonzack** [ryanseddon/gulp-es6-module-transpiler#27]
The npm version (0.2.0) only outputs a single `bundle.js` file no matter how many files are defined. Master appears to fix this. Can the version be bumped?

**Comment by janjakubnanista** [comment]
@ryanseddon could you npm-publish master branch pls?

**Comment by ryanseddon** [comment]
done. @janjakubnanista can you update the release history in the readme  please.

**Comment by janjakubnanista** [comment]
@ryanseddon I've updated the release history, please merge pull request #28
